### ISSUE TITLE
best way to clone node & have two instances of a controller running?

### ISSUE THREAD

**Issue by falafflepotatoe** [techlayer/espresso.js#14]
I'm trying to create two instances of 1 widget Box; is this the best way?

Also bug report? Its not working.

	<div id="appwrapper">
		<div id="app">
			<div data-ref="view"></div>
		</div>
	</div>

	var Box = Controller.extend({
		init:function(){},
		render:function(){
			return {
				view: { html: 'adsfasdfdsfadfsa' }
			}
		},
		click:function(){},
	})

	window.app = new Box({view: 'appwrapper' })
	window.app2 = new Box({ view: 'appwrapper' })
// nothing is displayed and no errors are given

// 	window.app = new Box({view: document.getElementById('app') })
// works

from the docs:
If options.view is a string, then it is used to locate the DOM node by ID and clone its first child. This is much faster than doing templating and parsing templates using innerHTML.

not sure if its not working or im doing it wrong. Chrome 33 on linux.

**Comment by falafflepotatoe** [comment]
I have one other question for you -- I'm doing emit wrong..

I wrote a quick fn to extend Collection; it changes every item in the collection,
mycollection.setAllKeyToValue('image', '')


heres the fn

	Collection = Collection.extend({
		setAllKeyToValue:function(key,value){
			for (var i = 0; i < this.items.length; i++){
				this.items[i][key] = value
				this.emit('change', { updated: this.items[i], index: i });
			}
		}
        })

im not getting the change event when i use it -- im not sure what im supposed to pass as the value for updated -- ive tried a few things here, maybe you can help?

**Comment by akrymski** [comment]
View refers to the current view element. You should not use that as a ref. change the ref name to something else.

**Comment by akrymski** [comment]
In the future, if you don't know how to do something please email me instead of opening an issue.  Also I suggest reading the source code as its very small, and is the best way to understand how everything works.

**Comment by akrymski** [comment]
works fine for me: http://jsfiddle.net/qz5p73yr/

make sure you add the event listener before calling setAllKeyToValue

**Comment by falafflepotatoe** [comment]
yea thanks for your help tho.

regarding the first issue i think it may be a bug. specifically/only the case where the view option is a string.

the docs say it should find that element and clone the first child, but nothing is happening in chrome.

http://jsfiddle.net/xccbhu7s/

remembering back from the source i think i saw you use something like cloneNode:true option -- maybe im forgetting to pass that option as well? (not sure if its listed in the docs)

**Comment by falafflepotatoe** [comment]
yea sorry i think i didnt understand the docs

|  If options.view is a string, then it is used to locate the DOM node by ID and clone its first child.

I understood this as you can create one template with html and clone it to as many widgets as you want -- i dont think thats possible nor the intention of that line of docs...

**Comment by akrymski** [comment]
that is the intention, you just not adding those views to the DOM after you instantiate them :) see this:

http://jsfiddle.net/xccbhu7s/1/

you can create a controller that is either bound to an existing DOM element:

window.app = new Box({view: document.getElementById('app')})

OR clones an existing element:

app = new Box({view: 'appwrapper' })

in which case the clone is in memory, you have to append it to the DOM, the same way render() returns a { list: new List(…) }

**Comment by falafflepotatoe** [comment]
ahh ok - thanks a bunch
