### ISSUE TITLE
Demo doesn't show item labels.

### ISSUE THREAD

**Issue by tvararu** [techlayer/espresso.js#15]
OS X 10.10.2 (14C109), Chrome Canary 43.0.2316.0 (64-bit).

![screen shot 2015-02-27 at 19 13 15](https://cloud.githubusercontent.com/assets/1650875/6419412/b4d06fb6-beb4-11e4-9b9b-ead83d25f9e1.png)

**Comment by akrymski** [comment]
Thanks, well spotted, managed to introduce that bug recently.  Fixed in the latest version.
