### ISSUE TITLE
REST requests?

### ISSUE THREAD

**Issue by gavinengel** [techlayer/espresso.js#17]
How should I integrate REST API calls to a with Espresso?  Are there any recommended libraries, or even examples?

**Comment by akrymski** [comment]
You can use any library you like to fetch data and update espresso collections/models.  Personally I like [superagent](https://github.com/visionmedia/superagent) and [fetch](http://github.github.io/fetch/) but jQuery's ajax function is fine too if you're already using jQuery in your project.  Example using superagent:
`
var collection = new Espresso.Collection();
request.get('/posts').end(function(err, res) {
  collection.set(res);
});
`

**Comment by gavinengel** [comment]
Thanks!
